//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCitt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.PERSONA = new HashSet<PERSONA>();
            this.CURSO = new HashSet<CURSO>();
        }
    
        public decimal IDUSUARIO { get; set; }
        public string NOMBREUSUARIO { get; set; }
        public string CONTRASEÑA { get; set; }
        public Nullable<decimal> IDESTADO { get; set; }
        public Nullable<decimal> IDTIPOUSUARIO { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual ICollection<PERSONA> PERSONA { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
        public virtual ICollection<CURSO> CURSO { get; set; }
    }
}
